- client/components/user-home.spec.js
- client/store/user.spec.js
- package-lock.json
- package.json
- script/seed.spec.js
- server/api/users.spec.js
- server/db/models/Product.js
- server/db/models/product.spec.js
- server/db/models/user.spec.js
Test suite for User and Product model
> Model tests

- client/components/AllProductsList.js
- client/components/Products.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- public/style.css
- script/seed.js
- server/api/index.js
- server/api/products.js
- server/db/models/Product.js
- server/db/models/user.js
* [] added AllProductsList/Products components
> feat(routers/products): all products render

- client/components/Products.js
- client/routes.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
added route to '/products'
> feat(route/products): add /products route

- server/db/models/user.spec.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Trying to get Travis to pass
> travis: activate deployment take 2

- .travis.yml
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Travis Take 3
> Travis Deploy Take 3

- script/seed.js
- server/db/index.js
- server/index.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Deployed!!!!!
> Export Models explicity

- server/db/models/index.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated file names for deploy
> updated file names

- script/seed.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Added passwords to seed file
> chore: adds passwords to seed file

- client/components/LandingPage.js
- client/components/SingleProduct.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- public/style.css
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Updated
- [] Deleted
- [] Added
- [] Deleted
- [] API route
- [] Model
- [] Component
Add LandingPage, changed the logo styling in nav bar and styling on singleProduct page
> feat(components): add landingPage, add styling

- client/components/CartItem.js
- client/components/navbar.js
- script/seed.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Improved cart functionality
> View cart items

- public/style.css
- server/auth/index.js
- server/db/models/index.js
- [] Added
- [] Deleted
- [] Added
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Added
- [] Deleted
- [] API route
- [] Model
- [] Component
updated all User model requires to be lowercase
> chore(git): updates user requires to be lowercase

- client/components/CartItem.js
- client/components/InsideCart.js
- client/store/cartItem.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Added correct quantities to cart view.
> Feat(components/viewcart: adds correct quantities of cart items

- server/api/guestCart.js
- [] Added
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
fixed /cart route for session store
> feat: fix session route for cart

- client/components/Products.js
- client/store/cartItem.js
- server/api/guestCart.js
- server/api/userCart.js
- server/db/models/CartItem.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
fixed typo in CartItem model
> Cartconnection

- server/api/userCart.js
- server/db/models/CartItem.js
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated userCart and guestCart
> feat: set all BE routes for usercart and guestcart , total missing

- server/api/userCart.js
- [] Added
- [] Deleted
- [] Models
- [] Added
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated seed file with priceAtPurchase added total to all userCart routes
> feat: add total to the userCart routes

- script/seed.js
- server/api/userCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated see file
> commit before merge

- client/components/CartItem.js
- client/components/InsideCart.js
- client/components/navbar.js
- client/store/cartItem.js
- package-lock.json
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
merge conflict on my end...sorry
> merge conflicts

- client/store/cartItem.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
> chore: fix store with spread operator

- client/store/cartItem.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
> Chore: fix store

- client/components/CartItem.js
- client/components/InsideCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
> Feat(component/insidecart): fixes cart view with new store

- client/components/CartItem.js
- client/components/InsideCart.js
- client/components/navbar.js
- client/components/user-home.js
- client/store/cartItem.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated store for delete route and cartItem count
> feat: update store delete cartItem route and fix cartcount

- client/components/AllProductsList.js
- client/components/CartItem.js
- client/components/InsideCart.js
- client/components/Products.js
- client/components/SingleProduct.js
- client/store/cartItem.js
- server/api/userCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [ x ] Routes/Components
- [] Added
- [ x ] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Adds ability to add items for logged in user, fixed quantity mechanism
> Adds ability to add items for logged in user

- client/components/Products.js
- client/components/SingleProduct.js
- client/store/cartItem.js
- server/api/guestCart.js
- server/db/models/GuestCart.js
- [] Added
- [] Deleted
- [] Models
- [] Added
- [] Deleted
**Redux**
- [] Added
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
added route for guests to add to cart
> feat: add guestcart route for add to cart

- client/components/AddProduct.js
- client/components/SingleProduct.js
- client/components/auth-form.js
- client/store/products.js
- client/store/user.js
- public/style.css
- server/api/products.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Sign Up function (hopefully) works! 
Also did styling on the Sign Up and Login forms
> Sign Up Form

- client/components/AdminDash.js
- client/components/Products.js
- client/routes.js
- client/store/allUsers.js
- client/store/products.js
- server/api/products.js
- server/api/users.js
- server/api/users.spec.js
- [] Added
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
added security so that only admins are able to access certain api and react routes. if a user tries to go to a route on the front end where they dont have access, the login page will appear. if a user tries to access a forbidden api route, "forbidden" appears
> Routes secure

- client/components/InsideCart.js
- client/store/cartItem.js
- server/api/guestCart.js
- server/db/models/index.js
- server/db/models/sessionCart/GuestCart.js
- [] Added
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
- [x ] session.cart
**Redux**
- [] Added
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
updated store (now action creator for user and guest separate)
updated the GuestCart constructor in the back (has now it's own folder)
router.delete for guestcart done and working with front end
> feat: update delete items from guest cart

- client/components/CartItemGuest.js
- client/components/CartItemUser.js
- client/components/InsideCart.js
- client/components/SingleProduct.js
- client/components/user-home.js
- client/store/cartItem.js
- client/store/user.js
- server/api/userCart.js
- server/db/models/sessionCart/GuestCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
added total to cart view for user and guest fixed some cart issues for user
> feat: add total to cart vies for user and guest

- client/components/CartItemGuest.js
- client/components/Products.js
- public/style.css
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Added
- [] Deleted
- [] API route
- [] Model
- [] Component
styled delete product admin button
> feat: add admin delete product button styling

- server/db/models/sessionCart/GuestCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
- [ x] SessionCart
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
added resetCart method on GuestCart
> feat: add resetCart method for GuestCart session

- client/components/CartItemGuest.js
- server/db/models/sessionCart/GuestCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
Accidentally mixed up CartItemUser and CartItemGuest in the middle of reverting quantity buttons. Hopefully, it's back to normal now.
> docs(components/GCartItemGuest): fix error hopefully

- client/components/CartItemUser.js
- client/components/InsideCart.js
- client/components/Products.js
- client/components/navbar.js
- client/components/user-home.js
- client/store/cartItem.js
- client/store/user.js
- server/api/guestCart.js
- server/auth/index.js
- server/index.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
fixed the issue with the cart batch for logged in users and guests
> feat: fix persistent cart batch for logged in user

- client/components/CartItemUser.js
- client/components/InsideCart.js
- client/store/cartItem.js
- public/style.css
- server/api/userCart.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Updated
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
> Feat(components/cart): adds increment/decrement

- client/components/Checkout.js
- [] Added
- [] Updated
- [] Deleted
- [] Models
- [] Added
- [] Updated
- [] Deleted
**Redux**
- [] Added
- [] Updated
- [] Deleted
**React**
- [] Added
- [] Deleted
- [] Styling
- [] Added
- [] Updated
- [] Deleted
- [] API route
- [] Model
- [] Component
GuestCart wasn't showing the proper cart details but it should be fixed now, I hope!
> Experiment
